### ISSUE TITLE
Float Pin icon to Right

### ISSUE THREAD

**Issue by rjmoggach** [kelszo/obsidian-file-explorer-plus#11]
### What would you like to be added?

Float the little pin icon on the right side of the frame instead of indenting to the left so as not to change/move the expected UI.

### Why is this needed?

Currently interrupts vertical columnar rhythm when there are custom icons or emojis on folders/files.

**Comment by rjmoggach** [comment]
this rudimentary hack is visually ok:

```css
.pin-icon {
    position: fixed;
    right: 5px !important;
}
```

> ![image](https://github.com/kelszo/obsidian-file-explorer-plus/assets/184759/e00662d4-b310-4bdc-ab82-9e1f67836805)

**Comment by kelszo** [comment]
This is a good idea, I will investigate it and most likely implement it

**Comment by mmshivesh** [comment]
Managed to make it look and function as if it was built into Obsidian with the following custom css snippet:

## Alternative 1

```css
.pin-icon {
    display: none;
    position: fixed;
    right: 20px !important;
}

.file-explorer-plus.pin-icon {
    margin-top: 0px;
    rotate: 0deg;
    color: var(--text-faint);
}

.tree-item-self:hover > .pin-icon {
    display: block;
}
```

![Screen Shot 2024-05-22 at 10 32 42 PM](https://github.com/kelszo/obsidian-file-explorer-plus/assets/23611514/4c1cdae8-65be-4c8f-aa5a-e461a8c6d627)

Benefits:
1. Very unobtrusive UI, shows up only when hovering
2. Uses the inbuilt --text-faint color, reducing visual clutter
3. Includes benefits of @rjmoggach's approach by having a clean Explorer view


## Alternative 2: Subtle animation

Tweaking the visibility on the pin lets me get a very subtle animation on the pin as well which makes it look super polished (can be made more subtle if necessary):

```css
.pin-icon {
    visibility: hidden;
    position: fixed;
    right: 20px !important;
}

.tree-item-self > .pin-icon {
    margin-top: -7px;
    visibility: hidden;
    rotate: 0deg;
    transition: visibility 0s, margin-top 0.1s ease-out;
    color: var(--text-faint);
}

.tree-item-self:hover > .pin-icon {
    visibility: visible;
    margin-top: 0;
}
```

![Screen Shot 2024-05-22 at 10 36 17 PM](https://github.com/kelszo/obsidian-file-explorer-plus/assets/23611514/d01d78ef-5dec-411c-809a-674b15b0491e)
