### ISSUE TITLE
Plugin stopped working for obsidian 1.60 

### ISSUE THREAD

**Issue by jorosy** [kelszo/obsidian-file-explorer-plus#19]
### What happened?

as title, no file is pin or filter for obsidian 1.60

### What did you expect to happen?

as title

### Can you reproduce the bug, if so how? As detailed but minimal as possible.

as title

### Plugin version

1.1.4

### Obsidian version

1.60

### OS

Windows

**Comment by Moyf** [comment]
I'm not sure but I can provide some changes that I found.

I used to use this css to add seperator in File Explorer:
```css
.nav-folder-children>[class*=nav-]:has([data-path="4-Archive"])::after,
.nav-folder-children>[class*=nav-]:has([data-path="_Inbox"])::after {
    content: '';
    display: block;
    height: 1px;
    width: calc(100% + 32px);
    background: var(--tab-outline-color);
    margin: var(--replete-custom-separators-vertical-padding) 0 var(--replete-custom-separators-vertical-padding) var(--replete-custom-separators-left-margin);
}
```

But now it also doesn't work.
And after change the `.nav-folder` like this:
```css
.nav-folder:has([data-path="4-Archive"])::after
```

It worked again.

So I think maybe OB did some class changes in version 1.6.0 🤔
