### ISSUE TITLE
ability to disable pin icon

### ISSUE THREAD

**Issue by beep-beep-beep-boop** [kelszo/obsidian-file-explorer-plus#27]
### What would you like to be added?

this plugin adds a pin icon on things that are pinned, but there isn't a setting to disable that currently. it can be hidden using a css snippet, but it could be nice having it as an option for people who don't want to deal with that.

```css
.file-explorer-plus.pin-icon {
  display: none !important;
}
```

### Why is this needed?

I use another plugin to add custom icons to notes, and I don't want there to be two icons on ones that are pinned.
